#!/bin/sh
set -eu

# Check formatting and lint
npx @biomejs/biome check --staged --files-ignore-unknown=true --no-errors-on-unmatched

# Sort package.json
if git diff --cached --name-only | grep --quiet "package.json"; then
		if ! npx --yes sort-package-json --quiet; then
				exit 1
		fi

		if ! git diff --quiet package.json; then
				git add package.json
		fi
fi

# Exit successfully
exit 0
